site_name: Pydantic CV
nav:
  - Home: index.md
theme:
  name: "material"

plugins:
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
